"""add password to user

Revision ID: 4e23913d2420
Revises: 80e76ec48226
Create Date: 2025-05-22 16:20:03.760517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e23913d2420'
down_revision: Union[str, None] = '80e76ec48226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
